#!/usr/bin/env ruby -Ku
# -*- coding: utf-8 -*-
# byte-compile from command line
# Needs Ruby 1.9.x
# forked from:
# http://d.hatena.ne.jp/rubikitch/20100107/bytecomp
EMACS = "emacs"
GLOBS = ["~/.emacs.d/init.el"]
DEFAULT_OPTS = ["-l", "cl", "-L", "."]
def extra_load_path(files)  # extract load-path from init files
  str = files.map do |file|
    begin
      File.read(file).scan(/add-to.+load-path.+"(.+?)"|push "(.+?)" load-path/)
    rescue
      next
    end
  end
  str.flatten.compact
end
load_path_opts = extra_load_path(GLOBS.map{|g| Dir[File.expand_path(g)]}.flatten).map{|f| ["-L", f]}.flatten
exec EMACS, "-Q", "-batch", *load_path_opts, *DEFAULT_OPTS, "-f", "batch-byte-compile", *ARGV
